"""empty message

Revision ID: 02802afe3c0e
Revises: 090f4c6c5def
Create Date: 2023-07-23 14:00:46.012255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02802afe3c0e'
down_revision = '090f4c6c5def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
